# Generated by Django 5.2.5 on 2025-08-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_organization_api_key_organization_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
